### ISSUE TITLE
v7.2.3

### ISSUE THREAD

**Issue by 977844579** [johnnync13/Xiaomi-Notebook-Air-1Gen#53] opened 2020-04-05 08:42 UTC
I used the latest boot driver, but I got the following error:
1.0cs: no schema for shr inkmemorymap at 12 index!
2.After closing the lid for a long time, I need to restart it.
Thank you.

**Comment by CoderSunflower** [comment] 2020-04-05 13:37
I have the same problem.
After closing the lid for a long time, sleep wake up doesn't work.
Here is the error report.

Sleep Wake failure in EFI

Failure code:: 0xffffffff 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2020-04-05 20:36:51 +0800
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   29

Data Source:      Stackshots
Shared Cache:     0xa777000 7A43B4A7-CD05-34AC-8EAC-FA230F67BD4E

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        darkwake=0 gfxrst=1

Time Awake Since Boot: 18s



Process:          swd [275]
Architecture:     x86_64
Footprint:        416 KB
Start time:       2020-04-05 20:36:51 +0800
End time:         2020-04-05 20:36:51 +0800
Num samples:      1 (1)

  Thread 0x6e5    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 109769) [0x7fff716e6cc9] 1
    1  ??? [0x108634454] 1
      1  ??? [0x1086341dd] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135862) [0x7fff718482b6] 1
         *1  ??? [0xffffff80002c8206] 1
           *1  ??? [0xffffff80009875f7] 1
             *1  ??? [0xffffff80008a0001] 1
               *1  ??? [0xffffff80002eb9e7] (running) 1

  Binary Images:
        0x7fff716cc000 -     0x7fff71702fff  libdyld.dylib (750.5)               <D2A07EF5-A64B-3692-BE13-89DAA2EC5E80>  /usr/lib/system/libdyld.dylib
        0x7fff71827000 -     0x7fff71853fff  libsystem_kernel.dylib (6153.101.6) <E76440E1-D1E8-3D9A-8B47-D01F554FF1C4>  /usr/lib/system/libsystem_kernel.dylib
Model: MacBookPro13,1, BootROM 243.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.4 GHz, 8 GB, SMC 2.36f98
Graphics: Skylake GT2 [HD Graphics 520], Skylake GT2 [HD Graphics 520], spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2133 MHz, Samsung, -
Bluetooth: Version 7.0.4f6, 3 services, 17 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Ethernet Adaptor (en3), Ethernet, en3
PCI Card: Skylake GT2 [HD Graphics 520], VGA compatible controller, Internal
PCI Card: Sunrise Point-LP USB 3.0 xHCI Controller, USB controller, Internal@0,20,0
PCI Card: Sunrise Point-LP SATA Controller [AHCI mode], SATA controller, Internal@0,23,0
PCI Card: Sunrise Point-LP CSME HECI #1, Communication controller, Internal@0,22,0
PCI Card: Sunrise Point-LP PMC, Memory controller, Internal@0,31,2
PCI Card: Sunrise Point-LP SMBus, SMBus, Internal@0,31,4
PCI Card: Sunrise Point-LP HD Audio, Audio device, Internal@0,31,3
PCI Card: Wireless 8260, Network controller, Internal@0,28,4/0,0
PCI Card: NVMe SSD Controller SM951/PM951, Non-Volatile memory controller, Internal@0,29,0/0,0
Serial ATA Device: WDC WDS120G2G0B-00EPW0, 120.04 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth HCI
USB Device: XiaoMi USB 2.0 Webcam
USB Device: 802.11ac NIC
Thunderbolt Bus: 


I hope it can help you.
Thank you.

**Comment by johnnync13** [comment] 2020-04-06 13:06
@CoderSunflower the problem is bluetooth kext. I can't do anything.

**Closed** 2020-04-06 13:06 UTC
